const translations = {
    en: {
        iconSet1: "Icon Set 1",
        iconSet2: "Icon Set 2",
        coopMode: "Cooperative mode",
        singleMode: "Single mode",
        createServer: "Create server",
        connectServer: "Connect to server",
        selectChapter: "Select chapter",
        selectMap: "Select map",
        serverPort: "Server port:",
        portNote: "Cannot be changed, the server must have this port open",
        timeout: "Connection timeout",
        timeoutNote: "Time to wait for player connection in seconds",
        startServer: "Start server",
        back: "Back",
        connect: "Connect",
        ipAddress: "IP Address:",
        launchCommand: "Launch command:",
        pleaseSelectChapterAndMap: "Please select a chapter and map.",
        pleaseEnterIP: "Please enter the server IP address.",
        errorExecutingCommand: "Error executing command:",
        commandExecutedSuccessfully: "Command executed successfully."
    },
    ru: {
        iconSet1: "Набор иконок 1",
        iconSet2: "Набор иконок 2",
        coopMode: "Кооперативный режим",
        singleMode: "Одиночный режим",
        createServer: "Создать сервер",
        connectServer: "Подключиться к серверу",
        selectChapter: "Выбор главы",
        selectMap: "Выбор карты",
        serverPort: "Порт сервера:",
        portNote: "Изменить нельзя, у сервера должен быть открыт этот порт",
        timeout: "Таймаут ожидания подключения",
        timeoutNote: "Время ожидания подключения игрока в секундах",
        startServer: "Запустить сервер",
        back: "Назад",
        connect: "Подключиться",
        ipAddress: "IP-адрес сервера:",
        launchCommand: "Команда запуска:",
        pleaseSelectChapterAndMap: "Пожалуйста, выберите главу и карту",
        pleaseEnterIP: "Пожалуйста, введите IP-адрес сервера.",
        errorExecutingCommand: "Ошибка при выполнении команды:",
        commandExecutedSuccessfully: "Команда успешно выполнена."
    }
};