const translations = {
    en: {
        iconSet1: "Icon Set 1",
        iconSet2: "Icon Set 2",
        coopMode: "Cooperative mode",
        singleMode: "Single mode",
        createServer: "Create server",
        connectServer: "Connect to server",
        selectChapter: "Select chapter",
        selectMap: "Select map",
        serverPort: "Server port:",
        portNote: "Cannot be changed, the server must have this port open",
        timeout: "Connection timeout",
        timeoutNote: "Time to wait for player connection in seconds",
        startServer: "Start server",
        back: "Back",
        connect: "Connect",
        ipAddress: "IP Address:",
        launchCommand: "Launch command:",
        pleaseSelectChapterAndMap: "Please select a chapter and map.",
        pleaseEnterIP: "Please enter the server IP address.",
        errorExecutingCommand: "Error executing command:",
        mp_wait_for_other_player_notconnecting_timeout: "Maximum time that we wait in the transition loading screen after we fully loaded for partner to start loading",
        mp_wait_for_other_player_timeout: "Maximum time that we wait in the transition loading screen for the other player",
        splitScreenMode: "Create split-screen without server",
        splitScreenInfo: "To play in split-screen mode, you need both a keyboard and a gamepad. After loading the level, press Z to switch the keyboard to the tall robot, while the gamepad control remains on the short robot. If the gamepad does not work, make sure that the Controller (Gamepad) option is set to 'Enabled' in the game settings. You can also play the game in this mode solo by switching keyboard control between characters using the Z key.",
        pleaseSelectMap: "Please select a map.",
    },
    ru: {
        iconSet1: "Набор иконок 1",
        iconSet2: "Набор иконок 2",
        coopMode: "Кооперативный режим",
        singleMode: "Одиночный режим",
        createServer: "Создать сервер",
        connectServer: "Подключиться к серверу",
        selectChapter: "Выбор главы",
        selectMap: "Выбор карты",
        serverPort: "Порт сервера:",
        portNote: "Изменить нельзя, у сервера должен быть открыт этот порт",
        timeout: "Таймаут ожидания подключения",
        timeoutNote: "Время ожидания подключения игрока в секундах",
        startServer: "Запустить сервер",
        back: "Назад",
        connect: "Подключиться",
        ipAddress: "IP-адрес сервера:",
        launchCommand: "Команда запуска:",
        pleaseSelectChapterAndMap: "Пожалуйста, выберите главу и карту",
        pleaseEnterIP: "Пожалуйста, введите IP-адрес сервера.",
        errorExecutingCommand: "Ошибка при выполнении команды:",
        mp_wait_for_other_player_notconnecting_timeout: "Максимальное время ожидания в экране загрузки после полной загрузки для начала загрузки партнера",
        mp_wait_for_other_player_timeout: "Максимальное время ожидания в экране загрузки для другого игрока",
        splitScreenMode: "Создать разделение экрана без сервера",
        splitScreenInfo: "Чтобы играть в режиме разделения экрана, нужно иметь и клавиатуру, и геймпад. После загрузки уровня нажмите Z, чтобы переключить клавиатуру на длинного робота, а управление геймпадом должно остаться на коротком роботе. Если геймпад не работает, убедитесь, что опция Контроллер (Геймпад) имеет статус 'Включено' в настройках игры. Также вы можете пройти игру в этом режиме в одиночку, просто переключая управление клавиатурой между персонажами на букву Z.",
        pleaseSelectMap: "Пожалуйста, выберите карту.",
    }
};